version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:19"
      timezone: "Europe/London"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:31"
      timezone: "Europe/London"
    allow:
      - dependency-type: "all"
