version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 3
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:19"
      timezone: "Europe/London"
    allow:
      - dependency-type: "all"
    rebase-strategy: disabled
  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(actions): "
    open-pull-requests-limit: 20
    rebase-strategy: disabled
    cooldown:
      default-days: 3
      exclude:
        - "quotidian-ennui/workflows-olio/*"
        - "quotidian-ennui/actions-olio/*"
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"
          - "quotidian-ennui/actions-olio/*"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:31"
      timezone: "Europe/London"
