set positional-arguments
set unstable
set script-interpreter := ['/usr/bin/env', 'bash']

# show recipes
[private]
@help:
    just --list --list-prefix "  "

# ./gradlew spotlessApply
[group("housekeeping")]
@fmt:
    ./gradlew --quiet spotlessApply
    just --fmt --unstable

# Generate and append vulnerability dismissals for aws-kms-csr
[group("housekeeping")]
[script]
suppress-vulns:
    #
    # shellcheck disable=SC1083
    set -eo pipefail

    tmp_file=$(mktemp)
    trap 'rm -f "$tmp_file"' EXIT

    gh my vulns -j \
      | grep -F 'aws-kms-csr' \
      | yq ea -p=json -o=yaml '
        . as $item ireduce ({};
          .[($item.CVE // $item.GHSA)].packages += [$item.package] |
          .[($item.CVE // $item.GHSA)].reason = "tolerable_risk" |
          .[($item.CVE // $item.GHSA)].comment = "Commandline one-shot tool; you are in control" |
          .[($item.CVE // $item.GHSA)].commentary = "autogenerated via just suppress-vulns"
        )
      ' - \
      | yq -o=yaml 'with_entries(.value.packages |= unique)' > "$tmp_file"

    yq ea -i '
      select(fileIndex == 0) *+ select(fileIndex == 1) |
      with_entries(.value.packages |= unique)
    ' .github/dismiss-alerts.yml "$tmp_file"
