name: dependabot-merge
#
# As of 2022-10-24-ish the standard GITHUB_TOKEN can't query the
# repo for protected branches, so this ridedott/merge-me-action
# is effectively unusable without a PAT
#
# Since we have no protected branches or private secrets that
# aren't accessible by depbot; we don't have to go this way
# We can use a fastify/github-merge instead (check gradle.yml)
# (technically since fastify/github-merge depends on some dependabot
# actions under the covers; that won't work UNLESS IT'S A PULL_REQUEST
# or PULL_REQUEST_TARGET which brings its own challenges...)
#
# Leaving the contents here as a reminder because the merge-me-action
# is still very useful if you have private github package registries
# (since dependabot won't have those secrets) but equally I don't want
# merge-me to use yet another PAT to be able to do the right thing.
#
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'check'

permissions: write-all

jobs:
  attempt-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      # As of 2022-07-[XX] workflow_run.conclusion is sometimes null.
      # It was the PR merge from 1.12.264 to 265
      # https://github.com/community/community/discussions/21090
      - name: Get workflow_run.conclusion
        uses: octokit/request-action@v2.1.9
        id: get_conclusion
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Check the action log, this will be a 200 OK but the
      # data will say forbidden in the same way that merge-me does.
      # This is effectively the same query that merge-me does under the covers.
      - name: can-query-protected-branches
        id: can-query-protected-branches
        continue-on-error: true
        run: |
          BRANCH_QUERY='{ repository(name: "aws-kms-csr", owner: "quotidian-ennui") { branchProtectionRules(first: 10) { edges { node { id } } } } }'
          GRAPH_QUERY=$(jq -n --arg q "$(echo $BRANCH_QUERY | tr -d '\n')" '{ query: $q}')
          curl -X POST \
          -si \
          -H "Accept: application/vnd.github.package-deletes-preview+json" \
          -H "Content-Type: application/json" \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          --data "$GRAPH_QUERY" \
          --url https://api.github.com/graphql
      - name: merge-if-build-success
        continue-on-error: true
        uses: ridedott/merge-me-action@v2
        if:  |
          github.event.workflow_run.conclusion == 'success' ||
          fromJson(steps.get_conclusion.outputs.data).conclusion  == 'success'
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          # GITHUB_TOKEN: ${{ secrets.MERGE_ME_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
