name: dependabot-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'check'

jobs:
  attempt-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: log conditions
        id: debug-step
        run: |
          echo "${{ github.event.workflow_run.conclusion }}"
          echo "${{ github.event.sender.login }}"
          echo "${{ github.ref_name }}"
      - name: merge-if-build-success
        uses: ridedott/merge-me-action@v2
        if: |
          github.event.workflow_run.conclusion == 'success' &&
          github.event.sender.login == 'dependabot[bot]' &&
          startsWith(github.ref_name, 'dependabot')
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
