name: dependabot-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'check'

jobs:
  attempt-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      # As of 2022-07-[XX] workflow_run.conclusion is sometimes null.
      # It was the PR merge from 1.12.264 to 265
      # https://github.com/community/community/discussions/21090
      - name: Get workflow_run.conclusion
        uses: octokit/request-action@v2.1.6
        id: get_conclusion
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: merge-if-build-success
        uses: ridedott/merge-me-action@v2
        if:  |
          github.event.workflow_run.conclusion == 'success' ||
          fromJson(steps.get_conclusion.outputs.data).conclusion  == 'success'
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
