name: check
run-name: Build ${{ github.event.client_payload.detail.pull_request }}
on:
  repository_dispatch:
    types:
      - pr-trigger
  push:
    branches:
      - master

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: setup-java
        uses: quotidian-ennui/actions-olio/setup-java-gradle@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          java-version: "21"
          distribution: "temurin"
          writeable: ${{ github.event.client_payload.detail.pull_request == '' }}
      - name: Build with Gradle
        run: |
          ./gradlew check

  dependabot-merge:
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
    if: github.event.client_payload.detail.pull_request != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          persist-credentials: false
      - name: "Create Token"
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: Repository Action Merge
        id: action_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
          merge_commentary: "Merge Workflow Actions"
      - name: Dependabot Merge
        id: merge_gradle_dependencies
        uses: quotidian-ennui/actions-olio/dependabot-merge@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: "**/*.gradle*,**/gradle-wrapper.properties,gradle/*.versions.toml,**/versions.properties"
          automerge_level: "semver-patch"
          merge_commentary: "Merge Gradle Dependencies"
          filter_separator: ","
