name: check
run-name: Build ${{ github.event.client_payload.detail.pull_request }}
on:
  repository_dispatch:
    types:
      - pr-trigger
  push:
    branches:
      - master

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: setup-java
        uses: quotidian-ennui/actions-olio/setup-java-gradle@553ec3b65772a6de54db9a6f48f07c16a7bd3823 # v1.3.1
        with:
          java-version: "21"
          distribution: "temurin"
          writeable: ${{ github.event.client_payload.detail.pull_request == '' }}
      - name: Build with Gradle
        run: |
          ./gradlew check

  dependabot-merge:
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
    if: github.event.client_payload.detail.pull_request != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          persist-credentials: false
      - name: "Create Token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: Repository Action Merge
        id: action_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@553ec3b65772a6de54db9a6f48f07c16a7bd3823 # v1.3.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
          merge_commentary: "Merge Workflow Actions"
      - name: Dependabot Merge
        id: merge_gradle_dependencies
        uses: quotidian-ennui/actions-olio/dependabot-merge@553ec3b65772a6de54db9a6f48f07c16a7bd3823 # v1.3.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: "**/*.gradle*,**/gradle-wrapper.properties,gradle/*.versions.toml,**/versions.properties"
          automerge_level: "semver-patch"
          merge_commentary: "Merge Gradle Dependencies"
          filter_separator: ","
