name: check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup-java
        uses: quotidian-ennui/actions-olio/setup-java-gradle@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          java-version: "21"
          distribution: "temurin"
          writeable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Build with Gradle
        run: |
          ./gradlew check

  dependabot-merge:
    needs: build
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@f3d61b485d2801773f7a07b2aaa3306bd8f8e653 # v1.3.5
        id: findpr
        with:
          github-token: ${{ github.token }}
          state: open
          sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
      - name: merge-if-built
        continue-on-error: true
        uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
        with:
          pr-number: ${{ steps.findpr.outputs.pr }}
          target: minor
