name: pr-trigger
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    name: PR Trigger
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@03ea351ebcd69c199efa11e7b2b10ab2cd7f8158 # v1.3.4
