name: pr-trigger
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    name: PR Trigger
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@20d61b495f9f57f9103dd8f052d5808370d5ce8b # v1.2.3
